/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPanel.java
 *
 * Created on Feb 24, 2010, 3:23:08 PM
 */
package com.googlecode.menugen.ui.menu;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang.math.NumberUtils;

import com.googlecode.menugen.domain.Recipe;
import com.googlecode.menugen.service.RecipeService;
import com.googlecode.menugen.utility.SpringContextUtility;

/**
 * 
 * @author tstavenger
 */
public class MenuPanel extends javax.swing.JPanel {
	private static final String LINE_SEPARATOR = System
			.getProperty("line.separator");

	/** Creates new form MenuPanel */
	public MenuPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOfMealsLabel = new javax.swing.JLabel();
        numberOfMealsText = new javax.swing.JTextField();
        servingsLabel = new javax.swing.JLabel();
        servingsText = new javax.swing.JTextField();
        createMenuButton = new javax.swing.JButton();
        meailsLabel = new javax.swing.JLabel();
        mealsSeparator = new javax.swing.JSeparator();
        shoppingListLabel = new javax.swing.JLabel();
        shoppingListSeparator = new javax.swing.JSeparator();
        mealsScrollPane = new javax.swing.JScrollPane();
        mealsTextArea = new javax.swing.JTextArea();
        shoppingListScrollPane = new javax.swing.JScrollPane();
        shoppingListTextArea = new javax.swing.JTextArea();

        numberOfMealsLabel.setText("Number of Meals:");

        servingsLabel.setText("Servings per Meal:");

        createMenuButton.setText("Create Menu");
        createMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuButtonActionPerformed(evt);
            }
        });

        meailsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        meailsLabel.setText("Meals");

        shoppingListLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shoppingListLabel.setText("Shopping List");

        mealsTextArea.setColumns(20);
        mealsTextArea.setRows(5);
        mealsScrollPane.setViewportView(mealsTextArea);

        shoppingListTextArea.setColumns(20);
        shoppingListTextArea.setRows(5);
        shoppingListScrollPane.setViewportView(shoppingListTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mealsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(createMenuButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberOfMealsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(numberOfMealsText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(servingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(servingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(meailsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mealsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shoppingListLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shoppingListSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shoppingListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfMealsLabel)
                    .addComponent(numberOfMealsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servingsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createMenuButton)
                .addGap(8, 8, 8)
                .addComponent(meailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shoppingListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void createMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createMenuButtonActionPerformed
		if (NumberUtils.isNumber(numberOfMealsText.getText())
				&& NumberUtils.isNumber(servingsText.getText())) {
			int numberOfMeals = Integer.parseInt(numberOfMealsText.getText());
			int servings = Integer.parseInt(servingsText.getText());
			List<Integer> servingsPerMeal = new ArrayList<Integer>(
					numberOfMeals);

			for (int i = 0; i < numberOfMeals; i++) {
				servingsPerMeal.add(servings);
			}

			this.menu = recipeService.createMenu(servingsPerMeal);
			StringBuilder meals = new StringBuilder();

			for (Recipe recipe : menu) {
				meals.append(recipe.getName());
				meals.append(LINE_SEPARATOR);
			}

			mealsTextArea.setText(meals.toString());
			
			List<String> shoppingList = recipeService.createShoppingList(menu);
			StringBuilder shopping = new StringBuilder();
			
			for (String string : shoppingList) {
				shopping.append(string);
				shopping.append(LINE_SEPARATOR);
			}
			
			shoppingListTextArea.setText(shopping.toString());			
		}
	}// GEN-LAST:event_createMenuButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createMenuButton;
    private javax.swing.JLabel meailsLabel;
    private javax.swing.JScrollPane mealsScrollPane;
    private javax.swing.JSeparator mealsSeparator;
    private javax.swing.JTextArea mealsTextArea;
    private javax.swing.JLabel numberOfMealsLabel;
    private javax.swing.JTextField numberOfMealsText;
    private javax.swing.JLabel servingsLabel;
    private javax.swing.JTextField servingsText;
    private javax.swing.JLabel shoppingListLabel;
    private javax.swing.JScrollPane shoppingListScrollPane;
    private javax.swing.JSeparator shoppingListSeparator;
    private javax.swing.JTextArea shoppingListTextArea;
    // End of variables declaration//GEN-END:variables

	private RecipeService recipeService = SpringContextUtility
			.getBean(RecipeService.class);
	private List<Recipe> menu;
}
