/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstructionPanel.java
 *
 * Created on Feb 15, 2010, 11:51:17 AM
 */

package com.googlecode.menugen.ui.recipe;

/**
 * 
 * @author tstavenger
 */
public class InstructionPanel extends javax.swing.JPanel {

	/** Creates new form InstructionPanel */
	public InstructionPanel(String instruction) {
		initComponents();

		stepText.setText(instruction);
	}

	public String getInstruction() {
		return stepText.getText();
	}

	/**
	 * Set the step number label.
	 * 
	 * @param step
	 *            int
	 */
	public void setStep(int step) {
		stepLabel.setText(step + ".");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		stepLabel = new javax.swing.JLabel();
		stepScrollPanel = new javax.swing.JScrollPane();
		stepText = new javax.swing.JTextArea();

		stepLabel.setText("1.");

		stepScrollPanel
				.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		stepText.setColumns(20);
		stepText.setRows(5);
		stepScrollPanel.setViewportView(stepText);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(stepLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												stepScrollPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												344,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				stepLabel).addComponent(stepScrollPanel,
				javax.swing.GroupLayout.PREFERRED_SIZE, 56,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel stepLabel;
	private javax.swing.JScrollPane stepScrollPanel;
	private javax.swing.JTextArea stepText;
	// End of variables declaration//GEN-END:variables

}
