/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on Feb 15, 2010, 11:24:12 AM
 */

package com.googlecode.menugen.ui.recipe;

import java.awt.FlowLayout;

import org.apache.commons.lang.math.NumberUtils;

import com.googlecode.menugen.domain.Recipe;
import com.googlecode.menugen.service.RecipeService;
import com.googlecode.menugen.utility.SpringContextUtility;

/**
 * 
 * @author tstavenger
 */
public class RecipePanel extends javax.swing.JPanel {

	private Recipe recipe;

	/** Creates new form NewJPanel */
	public RecipePanel() {
		initComponents();
	}

	public RecipePanel(Recipe recipe) {
		initComponents();

		instructionsPanel.setLayout(new VerticalFlowLayout(FlowLayout.LEFT));
		ingredientsPanel.setLayout(new VerticalFlowLayout(FlowLayout.LEFT));
		
		this.recipe = recipe;

		if (recipe != null) {
			populateValues();
		}
		
		
	}

	private void populateValues() {
		nameText.setText(recipe.getName());

		if (recipe.getServes() != null) {
			servesText.setText(String.valueOf(recipe.getServes()));
		}

		if (recipe.getPrepartionTime() != null) {
			prepTimeText.setText(String.valueOf(recipe.getPrepartionTime()));
		}

		if (recipe.getCookingTime() != null) {
			cookTimeText.setText(String.valueOf(recipe.getCookingTime()));
		}

		notesText.setText(recipe.getNotes());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        servesLabel = new javax.swing.JLabel();
        servesText = new javax.swing.JTextField();
        prepTimeLabel = new javax.swing.JLabel();
        prepTimeText = new javax.swing.JTextField();
        cookTimeLabel = new javax.swing.JLabel();
        cookTimeText = new javax.swing.JTextField();
        ingredientsSeparator = new javax.swing.JSeparator();
        ingredientsLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        instructionsSeparator = new javax.swing.JSeparator();
        notesLabel = new javax.swing.JLabel();
        notesSeparator = new javax.swing.JSeparator();
        notesScrollPane = new javax.swing.JScrollPane();
        notesText = new javax.swing.JTextArea();
        amountLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        ingredientLabel = new javax.swing.JLabel();
        ingredientsScrollPane = new javax.swing.JScrollPane();
        ingredientsPanel = new javax.swing.JPanel();
        instructionsScrollPane = new javax.swing.JScrollPane();
        instructionsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        addIngredientButton = new javax.swing.JButton();
        addStepButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 545));
        setRequestFocusEnabled(false);

        nameLabel.setText("Name:");

        servesLabel.setText("Serves:");

        prepTimeLabel.setText("Prep Time:");

        cookTimeLabel.setText("Cook Time:");

        ingredientsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        ingredientsLabel.setText("Ingredients");

        instructionsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instructionsLabel.setText("Instructions");

        notesLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        notesLabel.setText("Notes");

        notesScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        notesText.setColumns(20);
        notesText.setRows(5);
        notesScrollPane.setViewportView(notesText);

        amountLabel.setText("Amount");

        unitLabel.setText("Unit");

        ingredientLabel.setText("Ingredient");

        ingredientsPanel.setLayout(null);
        ingredientsScrollPane.setViewportView(ingredientsPanel);

        instructionsPanel.setLayout(null);
        instructionsScrollPane.setViewportView(instructionsPanel);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        addIngredientButton.setText("Add Ingredient");
        addIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientButtonActionPerformed(evt);
            }
        });

        addStepButton.setText("Add Step");
        addStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountLabel)
                        .addGap(36, 36, 36)
                        .addComponent(unitLabel)
                        .addGap(115, 115, 115)
                        .addComponent(ingredientLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(servesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servesText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prepTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prepTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cookTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cookTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ingredientsLabel)
                    .addComponent(ingredientsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(ingredientsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(addIngredientButton)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionsLabel)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(addStepButton)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesLabel)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(saveButton)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servesLabel)
                    .addComponent(servesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prepTimeLabel)
                    .addComponent(prepTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookTimeLabel)
                    .addComponent(cookTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ingredientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingredientsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(unitLabel)
                    .addComponent(ingredientLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingredientsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addIngredientButton)
                .addGap(7, 7, 7)
                .addComponent(instructionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStepButton)
                .addGap(12, 12, 12)
                .addComponent(notesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void addStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStepButtonActionPerformed
            instructionsPanel.add(new InstructionPanel());
            instructionsPanel.revalidate();
        }//GEN-LAST:event_addStepButtonActionPerformed

        private void addIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientButtonActionPerformed
            ingredientsPanel.add(new IngredientPanel());
            ingredientsPanel.revalidate();
        }//GEN-LAST:event_addIngredientButtonActionPerformed

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
		copyValues();

		this.recipe = recipeService.save(recipe);

		populateValues();
	}// GEN-LAST:event_saveButtonActionPerformed

	private void copyValues() {
		recipe.setName(nameText.getText());

		if (NumberUtils.isNumber(servesText.getText())) {
			recipe.setServes(Integer.valueOf(servesText.getText()));
		}

		if (NumberUtils.isNumber(prepTimeText.getText())) {
			recipe.setPrepartionTime(Double.valueOf(prepTimeText.getText()));
		}

		if (NumberUtils.isNumber(cookTimeText.getText())) {
			recipe.setCookingTime(Double.valueOf(cookTimeText.getText()));
		}

		recipe.setNotes(notesText.getText());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngredientButton;
    private javax.swing.JButton addStepButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel cookTimeLabel;
    private javax.swing.JTextField cookTimeText;
    private javax.swing.JLabel ingredientLabel;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JPanel ingredientsPanel;
    private javax.swing.JScrollPane ingredientsScrollPane;
    private javax.swing.JSeparator ingredientsSeparator;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JPanel instructionsPanel;
    private javax.swing.JScrollPane instructionsScrollPane;
    private javax.swing.JSeparator instructionsSeparator;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JSeparator notesSeparator;
    private javax.swing.JTextArea notesText;
    private javax.swing.JLabel prepTimeLabel;
    private javax.swing.JTextField prepTimeText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel servesLabel;
    private javax.swing.JTextField servesText;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables

	private RecipeService recipeService = SpringContextUtility
			.getBean(RecipeService.class);
}
