/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPanel.java
 *
 * Created on Feb 24, 2010, 3:23:08 PM
 */

package com.googlecode.menugen.ui.menu;

/**
 *
 * @author tstavenger
 */
public class MenuPanel extends javax.swing.JPanel {

    /** Creates new form MenuPanel */
    public MenuPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOfMealsLabel = new javax.swing.JLabel();
        numberOfMealsText = new javax.swing.JTextField();
        servingsLabel = new javax.swing.JLabel();
        servingsText = new javax.swing.JTextField();
        createMenuButton = new javax.swing.JButton();
        meailsLabel = new javax.swing.JLabel();
        mealsSeparator = new javax.swing.JSeparator();
        mealsScrollPane = new javax.swing.JScrollPane();
        mealsList = new javax.swing.JList();
        shoppingListLabel = new javax.swing.JLabel();
        shoppingListSeparator = new javax.swing.JSeparator();
        shoppingListScrollPane = new javax.swing.JScrollPane();
        shoppingList = new javax.swing.JList();
        createShoppingListButton = new javax.swing.JButton();

        numberOfMealsLabel.setText("Number of Meals:");

        servingsLabel.setText("Servings per Meal:");

        createMenuButton.setText("Create Menu");
        createMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuButtonActionPerformed(evt);
            }
        });

        meailsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        meailsLabel.setText("Meals");

        mealsScrollPane.setViewportView(mealsList);

        shoppingListLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shoppingListLabel.setText("Shopping List");

        shoppingListScrollPane.setViewportView(shoppingList);

        createShoppingListButton.setText("Create Shopping List");
        createShoppingListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createShoppingListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(mealsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(createMenuButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numberOfMealsLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(numberOfMealsText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(servingsLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(servingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(createShoppingListButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(shoppingListLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shoppingListSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addComponent(shoppingListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(mealsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(meailsLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfMealsLabel)
                    .addComponent(numberOfMealsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servingsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createMenuButton)
                .addGap(8, 8, 8)
                .addComponent(meailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createShoppingListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shoppingListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMenuButtonActionPerformed

    private void createShoppingListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShoppingListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createShoppingListButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createMenuButton;
    private javax.swing.JButton createShoppingListButton;
    private javax.swing.JLabel meailsLabel;
    private javax.swing.JList mealsList;
    private javax.swing.JScrollPane mealsScrollPane;
    private javax.swing.JSeparator mealsSeparator;
    private javax.swing.JLabel numberOfMealsLabel;
    private javax.swing.JTextField numberOfMealsText;
    private javax.swing.JLabel servingsLabel;
    private javax.swing.JTextField servingsText;
    private javax.swing.JList shoppingList;
    private javax.swing.JLabel shoppingListLabel;
    private javax.swing.JScrollPane shoppingListScrollPane;
    private javax.swing.JSeparator shoppingListSeparator;
    // End of variables declaration//GEN-END:variables

}
