/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on Feb 15, 2010, 11:24:12 AM
 */

package com.googlecode.menugen.ui.recipe;

import com.googlecode.menugen.domain.Recipe;

/**
 * 
 * @author tstavenger
 */
public class RecipePanel extends javax.swing.JPanel {

	private Recipe recipe;

	/** Creates new form NewJPanel */
	public RecipePanel() {
		initComponents();
	}

	public RecipePanel(Recipe recipe) {
		initComponents();

		this.recipe = recipe;

		if (recipe != null) {
			populateValues();
		}
	}

	private void populateValues() {
		nameText.setText(recipe.getName());

		if (recipe.getServes() != null) {
			servesText.setText(String.valueOf(recipe.getServes()));
		}

		if (recipe.getPrepartionTime() != null) {
			prepTimeText.setText(String.valueOf(recipe.getPrepartionTime()));
		}

		if (recipe.getCookingTime() != null) {
			cookTimeText.setText(String.valueOf(recipe.getCookingTime()));
		}

		notesText.setText(recipe.getNotes());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		nameLabel = new javax.swing.JLabel();
		nameText = new javax.swing.JTextField();
		servesLabel = new javax.swing.JLabel();
		servesText = new javax.swing.JTextField();
		prepTimeLabel = new javax.swing.JLabel();
		prepTimeText = new javax.swing.JTextField();
		cookTimeLabel = new javax.swing.JLabel();
		cookTimeText = new javax.swing.JTextField();
		ingredientsSeparator = new javax.swing.JSeparator();
		ingredientsLabel = new javax.swing.JLabel();
		instructionsLabel = new javax.swing.JLabel();
		instructionsSeparator = new javax.swing.JSeparator();
		notesLabel = new javax.swing.JLabel();
		notesSeparator = new javax.swing.JSeparator();
		notesScrollPane = new javax.swing.JScrollPane();
		notesText = new javax.swing.JTextArea();
		amountLabel = new javax.swing.JLabel();
		unitLabel = new javax.swing.JLabel();
		ingredientLabel = new javax.swing.JLabel();
		ingredientsScrollPane = new javax.swing.JScrollPane();
		ingredientsPanel = new javax.swing.JPanel();
		instructionsScrollPane = new javax.swing.JScrollPane();
		instructionsPanel = new javax.swing.JPanel();

		setPreferredSize(new java.awt.Dimension(400, 545));
		setRequestFocusEnabled(false);

		nameLabel.setText("Name:");

		nameText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameTextActionPerformed(evt);
			}
		});

		servesLabel.setText("Serves:");

		servesText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				servesTextActionPerformed(evt);
			}
		});

		prepTimeLabel.setText("Prep Time:");

		cookTimeLabel.setText("Cook Time:");

		cookTimeText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cookTimeTextActionPerformed(evt);
			}
		});

		ingredientsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
		ingredientsLabel.setText("Ingredients");

		instructionsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
		instructionsLabel.setText("Instructions");

		notesLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
		notesLabel.setText("Notes");

		notesScrollPane
				.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		notesText.setColumns(20);
		notesText.setRows(5);
		notesScrollPane.setViewportView(notesText);

		amountLabel.setText("Amount");

		unitLabel.setText("Unit");

		ingredientLabel.setText("Ingredient");

		javax.swing.GroupLayout ingredientsPanelLayout = new javax.swing.GroupLayout(
				ingredientsPanel);
		ingredientsPanel.setLayout(ingredientsPanelLayout);
		ingredientsPanelLayout.setHorizontalGroup(ingredientsPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 361, Short.MAX_VALUE));
		ingredientsPanelLayout.setVerticalGroup(ingredientsPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		ingredientsScrollPane.setViewportView(ingredientsPanel);

		javax.swing.GroupLayout instructionsPanelLayout = new javax.swing.GroupLayout(
				instructionsPanel);
		instructionsPanel.setLayout(instructionsPanelLayout);
		instructionsPanelLayout.setHorizontalGroup(instructionsPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 361, Short.MAX_VALUE));
		instructionsPanelLayout.setVerticalGroup(instructionsPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		instructionsScrollPane.setViewportView(instructionsPanel);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				amountLabel)
																		.addGap(
																				36,
																				36,
																				36)
																		.addComponent(
																				unitLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				128,
																				Short.MAX_VALUE)
																		.addComponent(
																				ingredientLabel)
																		.addGap(
																				120,
																				120,
																				120))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												nameLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												nameText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												339,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												servesLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												servesText,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												prepTimeLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												prepTimeText,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												cookTimeLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												cookTimeText,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												58,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								ingredientsLabel,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								ingredientsScrollPane,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE)
																						.addComponent(
																								ingredientsSeparator,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE))
																		.addContainerGap())
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				instructionsLabel)
																		.addContainerGap(
																				321,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				notesLabel)
																		.addContainerGap(
																				358,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								notesSeparator,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE)
																						.addComponent(
																								notesScrollPane,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE))
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								instructionsSeparator,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE)
																						.addComponent(
																								instructionsScrollPane,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								380,
																								Short.MAX_VALUE))
																		.addContainerGap()))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(nameLabel)
														.addComponent(
																nameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																servesLabel)
														.addComponent(
																servesText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																prepTimeLabel)
														.addComponent(
																prepTimeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																cookTimeLabel)
														.addComponent(
																cookTimeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(ingredientsLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												ingredientsSeparator,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(1, 1, 1)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																amountLabel)
														.addComponent(unitLabel)
														.addComponent(
																ingredientLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												ingredientsScrollPane,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(instructionsLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												instructionsSeparator,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												instructionsScrollPane,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(notesLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												notesSeparator,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												notesScrollPane,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(18, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameTextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_nameTextActionPerformed

	private void servesTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_servesTextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_servesTextActionPerformed

	private void cookTimeTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cookTimeTextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cookTimeTextActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel amountLabel;
	private javax.swing.JLabel cookTimeLabel;
	private javax.swing.JTextField cookTimeText;
	private javax.swing.JLabel ingredientLabel;
	private javax.swing.JLabel ingredientsLabel;
	private javax.swing.JPanel ingredientsPanel;
	private javax.swing.JScrollPane ingredientsScrollPane;
	private javax.swing.JSeparator ingredientsSeparator;
	private javax.swing.JLabel instructionsLabel;
	private javax.swing.JPanel instructionsPanel;
	private javax.swing.JScrollPane instructionsScrollPane;
	private javax.swing.JSeparator instructionsSeparator;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameText;
	private javax.swing.JLabel notesLabel;
	private javax.swing.JScrollPane notesScrollPane;
	private javax.swing.JSeparator notesSeparator;
	private javax.swing.JTextArea notesText;
	private javax.swing.JLabel prepTimeLabel;
	private javax.swing.JTextField prepTimeText;
	private javax.swing.JLabel servesLabel;
	private javax.swing.JTextField servesText;
	private javax.swing.JLabel unitLabel;
	// End of variables declaration//GEN-END:variables

}
